### PR TITLE
Build Fixes #5

### LINKED ISSUE #5: Build fails
```
fd_init.c:18:10: fatal error: freeDiameter/freeDiameter-host.h: No such file or directory
 #include <freeDiameter/freeDiameter-host.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Add the relevant submodule from c3po or move openmme into c3po to leverage the pre-existing scripts, deps

### PR DESCRIPTION
**Pull request by amitinfo2k**
--Added freediameter module dependancy
--Added install.sh utility script

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by krsna1729** [comment]
@amitinfo2k can we skip the install.sh? and have install_builddeps.sh and install_rundeps.sh like here 
https://github.com/krsna1729/c3po/tree/docker
https://github.com/krsna1729/ngic-rtc/tree/18.04-docker

Dont think we should worry about the users proxy requirements and no real reason to have it interactive. 
Simple straightforward scripts that can be included in any toolchain

**Comment by krsna1729** [comment]
also not sure if we should have this banner
```
# The software in this package is published under the terms of the Commercial
# Free Software license V.1, a copy of which has been included with this
# distribution in the LICENSE.md file.
#
```

**Comment by krsna1729** [comment]
@amitinfo2k any update on this?

**Review by krsna1729 — CHANGES_REQUESTED** [review]
Please address the two points

**Comment by krsna1729** [comment]
installation script has been addressed by https://github.com/omec-project/openmme/pull/19
Still need the submodule part though

**Pull request closed without merging**
