### PR TITLE
add pti feature

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by krsna1729 — COMMENTED** [review]
Needs commit message.
Remove commented out blocks if they are incorrect

**Comment by ghost** [comment]
retest this please

**Comment by ghost** [comment]
retest this please

**Review by badhrinathpa — COMMENTED** [review]
This fix for attach looks ok. We would need similar fix for detach and the Bearer resource command also. we can update as part of another patch.

**Review by vbarate — APPROVED** [review]

**Pull request merged**
