### PR TITLE
use the gtp port configured in s11 config file

### PR DESCRIPTION
**Pull request by ghost**
Current code does not use the port configured in config file

### CODE REVIEW

**Review by thakurajayL — APPROVED** [review]
Need similar changes in paging branch as well.

**Comment by pingping-lin** [comment]
> Need similar changes in paging branch as well.



> Need similar changes in paging branch as well.

**Comment by ghost** [comment]
> Need similar changes in paging branch as well.
also pushed to paging branch.

**Comment by ghost** [comment]
retest this please

**Comment by ghost** [comment]
tested with ng40+staging pod.

**Pull request merged**
