### PR TITLE
update license for Makefiles and scripts

### PR DESCRIPTION
**Pull request by ghost**
(1) use short license header
 (2) add SPDX-License-Identifier Apache-2.0
 (3) to pass the reuse tool test in jenkins

### CODE REVIEW

**Comment by sindack** [comment]
retest this please

**Comment by ghost** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Comment by sindack** [comment]
retest this please

**Comment by yoooou** [comment]
CI job failure is not related to this patch. Force merge it for now

**Review by sindack — APPROVED** [review]

**Pull request merged**
