### PR TITLE
Fixing stream id and relative capacity

### PR DESCRIPTION
**Pull request by thakurajayL**
Fixing relative capacity in mme was set to 0 because of which eNB can not initiated new connections to MME. Stream id was not set to 0 in the s1ap setup response, so eNB was not handling the s1ap setup response and because of which UE was not able to send  attach request to MME through eNB

### CODE REVIEW

**Comment by thakurajayL** [comment]
retest this please

**Comment by thakurajayL** [comment]
reset this please

**Comment by yoooou** [comment]
retest this please

**Comment by yoooou** [comment]
retest this please

**Review by badhrinathpa — COMMENTED** [review]
+1

**Pull request merged**
