### PR TITLE
#7 json help added under readme

### PR DESCRIPTION
**Pull request by vbarate**
OpenMME applications configuration help added under Readme.
Reference #7

### CODE REVIEW

**Comment by micpez** [comment]
@vbarate , should there be a section for s6a_fd.conf as well?

**Comment by vbarate** [comment]
s6a_fd.conf is common freediameter configuration. freediameter help can be referred for that 
http://www.freediameter.net/trac/wiki/Configuration
I think in the same file(s6a_fd.conf) we can add this link for clarity.

**Comment by krsna1729** [comment]
@vbarate looks good. too bad json doesnt allow comments, else we could have documented in the respective config files itself :P

**Comment by krsna1729** [comment]
any thoughts about would a README.md in each of the folder be better vs top-level one?

**Comment by vbarate** [comment]
> @vbarate looks good. too bad json doesnt allow comments, else we could have documented in the respective config files itself :P
@krsna1729 Yes. This was warned by  while deciding on json.

> any thoughts about would a README.md in each of the folder be better vs top-level one?
As of now, there is not much to document at an individual module level.

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
@vbarate, tests fail because it cannot rebase the patch on master:
```
git fetch origin pull/10/head:jenkins_test
git rebase master jenkins_test

Cloning into 'openmme'...
From https://github.com/omec-project/openmme
 * [new ref]         refs/pull/10/head -> jenkins_test
error: Failed to merge in the changes.
```
Could you please rebase and push again?

**Pull request merged**
