### PR TITLE
Create scripts in .ci dir to install openmme

### PR DESCRIPTION
**Pull request by micpez**
Move install step logic from groovy file to bash scripts in .ci directory in openmme repo.

### CODE REVIEW

**Comment by micpez** [comment]
retest this please

**Review by Sandeep-Sarma — COMMENTED** [review]
Can we have a naming convention of this script file (.ci/scripts/install.config) similar to the others aka xxx.sh? Eg: install_config.sh

**Comment by krsna1729** [comment]
@micpez what about TC1 and TC2 files?
https://github.com/omec-project/omec-project-ci/pull/37

**Comment by micpez** [comment]
retest this please

**Comment by micpez** [comment]
retest this please

**Comment by krsna1729** [comment]
@omec-project/openmme-maintainers

**Comment by micpez** [comment]
This shall be merged together with https://github.com/omec-project/omec-project-ci/pull/37

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
